version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: valles_mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: usuario@1
      MYSQL_DATABASE: valles_db
      MYSQL_USER: asier
      MYSQL_PASSWORD: usuario@1
    volumes:
      - /home/ubuntu/Proyecto/ASGBD/sql/proyecto.sql:/docker-entrypoint-initdb.d/proyecto.sql
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
